### ISSUE TITLE
Returned ServiceFactory objects are not checked for validity

### ISSUE THREAD

**Issue by saschazelzer** [CppMicroServices/CppMicroServices#221] opened 2017-07-13 05:30 UTC
When the framework creates a service object via a service factory, the returned service object is only checked to be non-null and non-empty. It is not checked if the returned interface map contains interface pointers for all registered object classes.

**Comment by karthikreddy09** [comment] 2019-03-21 15:36
I do not think this is a valid issue. I found the following code in `ServiceReferenceBasePrivate::GetServiceFromFactory`

```
for (auto clazz : classes) {
      if (smap->find(clazz) == smap->end() &&
          clazz != "org.cppmicroservices.factory") {
        std::string message(
          "ServiceFactory produced an object that did not implement: " + clazz);
        registration->bundle->coreCtx->listeners.SendFrameworkEvent(
          FrameworkEvent(
            FrameworkEvent::Type::FRAMEWORK_WARNING,
            MakeBundle(bundle->shared_from_this()),
            message,
            std::make_exception_ptr(std::logic_error(message.c_str()))));
        return nullptr;
      }
    }
```

I will write up a test case to verify.

**Comment by karthikreddy09** [comment] 2019-03-21 19:57
confirmed this issue is invalid with the following test

TEST(ServiceFactoryTest, TestWithInvalidReturnValue)
{
  FrameworkFactory factory;
  auto framework = factory.NewFramework();
  framework.Start();
  auto context = framework.GetBundleContext();

  auto sf = std::make_shared<MockFactory>();
  EXPECT_CALL(*sf, GetService(testing::_, testing::_)).Times(testing::AtLeast(1)).WillRepeatedly(testing::Invoke([](const Bundle & bundle, const ServiceRegistrationBase & reg) {
    // return an InterfaceMap with insufficient interfaces
    std::shared_ptr<ITestServiceA> implPtr = std::make_shared<TestServiceP>();
    return MakeInterfaceMap<ITestServiceA>(implPtr);
  }));
  EXPECT_CALL(*sf, UngetService(testing::_, testing::_, testing::_)).Times(0);

  ServiceRegistration<ITestServiceA, ITestServiceB> reg1 =
    context.RegisterService<ITestServiceA, ITestServiceB>(ToFactory(sf), { { Constants::SERVICE_SCOPE, Any(Constants::SCOPE_PROTOTYPE) } });

  auto sref1 = context.GetServiceReference<ITestServiceA>();
  ASSERT_TRUE((bool)sref1);
  FrameworkEvent lastEvent;
  context.AddFrameworkListener([&lastEvent](const cppmicroservices::FrameworkEvent& evt) {
    lastEvent = evt;
  });
  ASSERT_EQ(context.GetService<ITestServiceA>(sref1), nullptr);
  ASSERT_EQ(lastEvent.GetType(), FrameworkEvent::FRAMEWORK_WARNING);
  auto sref2 = context.GetServiceReference<ITestServiceB>();
  ASSERT_TRUE((bool)sref2);
  ASSERT_EQ(context.GetService<ITestServiceB>(sref2), nullptr);
  ASSERT_EQ(lastEvent.GetType(), FrameworkEvent::FRAMEWORK_WARNING);
}

I can't add the testpoint as I wrote it because it depends on googlemock which is not in the "thirdparty" folder.

Closing this issue with 2 new issues created 
1. issue#327 - Add GoogleMock to the "thirdparty" folder
2. issue#328Add a test point to validate the return value from ServiceFactory::GetService call

**Closed by karthikreddy09** 2019-03-21 19:57 UTC
Labels: bug
