### ISSUE TITLE
LDAPFilter::Match throws std::runtime_error if a bundle contains a key that is a leading substring of another key

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#227] opened 2017-08-14 18:56 UTC
Calling LDAPFilter::Match on a bundle that contains the keys: 

```
"apple" : "granny smith" 
"applesauce" : "yum" 
```

throws a std::runtime_error when creating an instance of cppmicroservices::Properties because Properties::Find_unlocked only does a strncasecmp of key.size() between key and keys[i]. 

Properties::Find_unlocked should check that the sizes of the two strings are equal before reporting duplicate keys and any exceptions thrown by Properties should be swallowed by LDAPFilter::Match before returning false since Match isn't supposed to throw exceptions.

**Comment by ksubramz** [comment] 2017-08-16 14:03
The way this bug manifests is worth documenting - it's dependent on 
 - if a key is a substring of another key, and 
 - the AnyMap iteration order in `Properties` constructor.. specifically the line:

`
  for (auto& iter : p)
`
in `Properties::Properties(const AnyMap& p)`

Suppose the range-based iterator gives out the key `apple` first and `applesauce` next, there is no exception triggered. However, if the iterator gives out the key `applesauce` first and then the key `apple`, the `Properties::Find_unlocked` call in the constructor does a strncasecmp of the key in question `apple` and the first 5 characters of `applesauce`, which is `apple` and throws an exception because they are equal.

It turns out I can't reproduce the bug with the keys specified in the Issue, however I can reproduce the bug with different sets of keys i.e. `hosed`, `hosedd`, `hose`

**Comment by ksubramz** [comment] 2017-08-24 15:56
Merged.

**Closed by ksubramz** 2017-08-24 15:56 UTC
Labels: bug
